### ISSUE TITLE
Suggestions for the workshop front end

### ISSUE THREAD

**Issue by ajuanjojjj** [demoran23/Exacting#5]
Cant post comments in the workshop page, idk if thats because having a "fresh" account, or because they've been disabled. If its the latter, enabling them would probably make many people want to share experiences or suggestions.

On top of that, i've seen thats there's so much more info here than in the workshop, on top of no images of the mod ingame. Thats the first thing that anyone sees when they click on the link, and "A slay the spire mod"doesnt really explain nothing about what it does. 

I love the idea and sounds amazing, but i fear that the lack of visibility may harm the actual traction it gets

**Comment by demoran23** [comment]
@ajuanjojjj I had at one point put all of the detail in the README.md in the Steam Worshop, but I felt like it was a bit overwhelming and the basic descriptions, without the specifics, would be enough for people to make a decision on.  Perhaps I'll note there that more detail is available here.

**Comment by ajuanjojjj** [comment]
Sure, maybe all the info is too much to display all text, but you could place some examples as photos, that would probably make it all the more attractive

I know that people will value the presentation and overall look way more than the actual content, which a lot of us devs usually forget :)
